### ISSUE TITLE
Cursor in output field

### ISSUE THREAD

**Issue by narley** [tim-crisp/javascript.lol#9]
When selected, the output field displays a cursor but doesn't allow to type.
And also the borders get highlighted.

**Comment by tim-crisp** [comment]
A text area (with cursor) was originally used to allow people to have better control over what they want to select if using keyboard. Are your thoughts to hide the cursor and prevent borders from being highlighted?

**Comment by narley** [comment]
Thanks for explaining. I see the benefit of having the cursor. I'll close this issue.
